displayName: mTLS To Headers
type: middleware
iconPath: .assets/icon.png

import: github.com/Sammy1Am/traefik-mtlstoheaders-plugin

summary: 'mTLS To Headers'

testData:
  Headers:
    X-Demo: test
    X-URL: '{{URL}}'
